/*
 * Copyright 2026 Neuraville Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

package io.feagi.sdk.pns.outputs;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Text stream output for language generation.
 *
 * <p>This class represents a stream of text generated by FEAGI. It can be used
 * for chatbots, text generation, natural language output, etc.</p>
 *
 * <p>Example usage:</p>
 * <pre>{@code
 * OutputTextStream textOut = OutputTextStream.builder()
 *     .maxTextLength(256)
 *     .encoding("UTF-8")
 *     .build();
 *
 * textOut._registerWithCache();
 *
 * // In main loop
 * while (true) {
 *     textOut._readFromCache();
 *     String generatedText = textOut.getText();
 *     System.out.println("FEAGI: " + generatedText);
 * }
 * }</pre>
 *
 * @see BaseOutput
 * @see OutputNumericStream
 */
public class OutputTextStream extends BaseOutput {

    /**
     * Maximum text length.
     */
    private final int maxTextLength;

    /**
     * Character encoding.
     */
    private final String encoding;

    /**
     * Whether to keep text history.
     */
    private final boolean keepHistory;

    /**
     * Current generated text from FEAGI.
     */
    private String currentText;

    /**
     * Text history (if keepHistory is enabled).
     */
    private final List<String> textHistory;

    /**
     * Creates a new OutputTextStream with the specified configuration.
     *
     * @param builder the builder containing configuration values
     */
    private OutputTextStream(Builder builder) {
        this.maxTextLength = builder.maxTextLength;
        this.encoding = builder.encoding;
        this.keepHistory = builder.keepHistory;
        this.currentText = "";
        this.textHistory = new ArrayList<>();
    }

    /**
     * Create a builder for OutputTextStream configuration.
     *
     * @return a new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Get the maximum text length.
     *
     * @return the maximum length
     */
    public int maxTextLength() {
        return maxTextLength;
    }

    /**
     * Get the character encoding.
     *
     * @return the encoding string
     */
    public String encoding() {
        return encoding;
    }

    /**
     * Check if text history is enabled.
     *
     * @return true if history is kept, false otherwise
     */
    public boolean isKeepHistory() {
        return keepHistory;
    }

    /**
     * Get the current generated text from FEAGI.
     *
     * @return the current text
     */
    public String getText() {
        return currentText;
    }

    /**
     * Get the text history (unmodifiable view).
     *
     * @return unmodifiable list of text history, or empty list if keepHistory is false
     */
    public List<String> getTextHistory() {
        if (keepHistory) {
            return Collections.unmodifiableList(textHistory);
        }
        return Collections.emptyList();
    }

    /**
     * Get the number of texts in history.
     *
     * @return the history size
     */
    public int historySize() {
        return textHistory.size();
    }

    /**
     * Process text from FEAGI.
     *
     * @param text the text from FEAGI
     */
    public void processText(String text) {
        if (text == null) {
            throw new NullPointerException("text must not be null");
        }

        // Truncate if exceeds max length
        if (text.length() > maxTextLength) {
            text = text.substring(0, maxTextLength);
        }

        this.currentText = text;

        // Add to history if enabled
        if (keepHistory && !text.isEmpty()) {
            textHistory.add(text);
        }
    }

    /**
     * Append text to the current text.
     *
     * @param text the text to append
     */
    public void appendText(String text) {
        if (text == null) {
            throw new NullPointerException("text must not be null");
        }

        String newText = currentText + text;

        // Truncate if exceeds max length
        if (newText.length() > maxTextLength) {
            newText = newText.substring(newText.length() - maxTextLength);
        }

        this.currentText = newText;

        // Add to history if enabled
        if (keepHistory && !text.isEmpty()) {
            textHistory.add(text);
        }
    }

    /**
     * Clear the current text and history.
     */
    public void clear() {
        this.currentText = "";
        if (keepHistory) {
            textHistory.clear();
        }
    }

    /**
     * Encode text to bytes.
     *
     * @param text the text to encode
     * @return the encoded byte array
     */
    public byte[] encodeText(String text) {
        Objects.requireNonNull(text, "text must not be null");
        return text.getBytes(StandardCharsets.UTF_8);
    }

    /**
     * Decode bytes to text.
     *
     * @param data the byte array to decode
     * @return the decoded text
     */
    public String decodeText(byte[] data) {
        Objects.requireNonNull(data, "data must not be null");
        return new String(data, StandardCharsets.UTF_8);
    }

    /**
     * Get simple word-level tokens.
     *
     * @param text the text to tokenize
     * @return list of word tokens
     */
    public List<String> tokenizeWords(String text) {
        Objects.requireNonNull(text, "text must not be null");
        String[] words = text.split("\\s+");
        List<String> result = new ArrayList<>();
        for (String word : words) {
            if (!word.isEmpty()) {
                result.add(word);
            }
        }
        return result;
    }

    @Override
    protected void _registerWithCache() {
        // Register text stream with FEAGI cache system
        // In a full implementation, this would:
        // 1. Register with NPU for text output
        // 2. Configure tokenizer settings
        // 3. Set up motor group and channel

        // For now, just mark as registered with default group
        markRegistered(0);
    }

    @Override
    protected void _readFromCache() {
        // Read generated text from FEAGI cache
        // In a full implementation, this would:
        // 1. Read text data from shared memory region
        // 2. Decode and process through processText()
        // 3. Update currentText

        // For now, this is a no-op
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        OutputTextStream that = (OutputTextStream) o;

        if (maxTextLength != that.maxTextLength) return false;
        if (keepHistory != that.keepHistory) return false;
        if (!Objects.equals(currentText, that.currentText)) return false;
        if (!Objects.equals(encoding, that.encoding)) return false;
        return Objects.equals(groupId, that.groupId);
    }

    @Override
    public int hashCode() {
        int result = maxTextLength;
        result = 31 * result + (encoding != null ? encoding.hashCode() : 0);
        result = 31 * result + (keepHistory ? 1 : 0);
        result = 31 * result + (currentText != null ? currentText.hashCode() : 0);
        result = 31 * result + (groupId != null ? groupId.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "OutputTextStream{" +
            "maxTextLength=" + maxTextLength +
            ", encoding='" + encoding + '\'' +
            ", keepHistory=" + keepHistory +
            ", currentText='" + truncate(currentText, 20) + '\'' +
            ", historySize=" + textHistory.size() +
            ", groupId=" + groupId +
            '}';
    }

    /**
     * Truncate a string for display.
     *
     * @param s the string to truncate
     * @param length the maximum length
     * @return the truncated string with "..." if applicable
     */
    private String truncate(String s, int length) {
        if (s == null || s.length() <= length) {
            return s;
        }
        return s.substring(0, length) + "...";
    }

    /**
     * Builder for OutputTextStream configuration.
     */
    public static final class Builder {
        private int maxTextLength = 256;
        private String encoding = "UTF-8";
        private boolean keepHistory = false;

        private Builder() {}

        /**
         * Validate that a numeric value is positive.
         */
        private void validatePositive(int value, String fieldName) {
            if (value <= 0) {
                throw new IllegalArgumentException(fieldName + " must be positive, got: " + value);
            }
        }

        /**
         * Validate that a string is not null or empty.
         */
        private void validateNotEmpty(String value, String fieldName) {
            if (value == null) {
                throw new NullPointerException(fieldName + " must not be null");
            }
            if (value.isEmpty()) {
                throw new IllegalArgumentException(fieldName + " must not be empty");
            }
        }

        /**
         * Set the maximum text length.
         *
         * @param maxTextLength the maximum length (must be positive)
         * @return this builder
         * @throws IllegalArgumentException if maxTextLength is not positive
         */
        public Builder maxTextLength(int maxTextLength) {
            validatePositive(maxTextLength, "maxTextLength");
            this.maxTextLength = maxTextLength;
            return this;
        }

        /**
         * Set the character encoding.
         *
         * @param encoding the encoding string (e.g., "UTF-8", "ASCII")
         * @return this builder
         * @throws NullPointerException if encoding is null
         * @throws IllegalArgumentException if encoding is empty
         */
        public Builder encoding(String encoding) {
            validateNotEmpty(encoding, "encoding");
            this.encoding = encoding;
            return this;
        }

        /**
         * Enable or disable text history.
         *
         * @param keepHistory true to keep history, false otherwise
         * @return this builder
         */
        public Builder keepHistory(boolean keepHistory) {
            this.keepHistory = keepHistory;
            return this;
        }

        /**
         * Build the OutputTextStream instance.
         *
         * @return a new OutputTextStream with the configured values
         */
        public OutputTextStream build() {
            return new OutputTextStream(this);
        }
    }
}
